name: Docker Image CI

on:
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Log in to ghcr.io with docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push docker containers
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./envs/Dockerfile
          push: False 
          tags: |
            ${{ steps.meta.outputs.tags }}
